services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: politica_electoral_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: politica_electoral
      POSTGRES_USER: politica
      POSTGRES_PASSWORD: politica_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U politica -d politica_electoral"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: politica_electoral_redis
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
